FROM registry.fedoraproject.org/fedora:37

RUN dnf install \
--setopt=tsflags= \
-y \
koji \
koji-hub \
koji-web \
koji-hub-plugins \
curl \
httpd \
mod_ssl \
postgresql \
fedora-messaging \
python3-mod_wsgi

RUN rm -f /etc/kojiweb/web.conf && \
ln -s /etc/koji-hub/kojiweb.conf /etc/kojiweb/web.conf
RUN chown -R 1001:root /etc/koji-hub && \
chown -R 1001:root /etc/pki/tls
RUN mkdir -p /var/cache/kojihub && \
chown -R 1001:root /var/cache/kojihub

COPY files/readiness.sh /readiness.sh
COPY files/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh /readiness.sh && \
chown 1001:root /entrypoint.sh /readiness.sh

ENV USER=1001
USER 1001

ENTRYPOINT bash /entrypoint.sh
